name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']
    
    name: Ruby ${{ matrix.ruby-version }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
    
    - name: Run tests
      run: |
        mkdir -p tmp
        bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec.xml
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: rspec-results-${{ matrix.ruby-version }}
        path: tmp/rspec.xml

  lint:
    runs-on: ubuntu-latest
    name: Code Quality
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
    
    - name: Run StandardRB
      run: |
        bundle exec standardrb --format github
    
    - name: Check gem build
      run: |
        gem build secvault.gemspec