name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'unnitallman/secvault'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3
    
    - name: Run tests
      run: |
        bundle exec rspec
    
    - name: Build gem
      run: |
        gem build secvault.gemspec
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          secvault-*.gem
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}